// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentType int32

const (
	PaymentType_PaymentDefault PaymentType = 0
	PaymentType_PaymentHold    PaymentType = 1
)

var PaymentType_name = map[int32]string{
	0: "PaymentDefault",
	1: "PaymentHold",
}

var PaymentType_value = map[string]int32{
	"PaymentDefault": 0,
	"PaymentHold":    1,
}

func (x PaymentType) String() string {
	return proto.EnumName(PaymentType_name, int32(x))
}

func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

type CreateOrderRequest struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Type                 int32                `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	VisitUuid            string               `protobuf:"bytes,4,opt,name=visit_uuid,json=visitUuid,proto3" json:"visit_uuid,omitempty"`
	StreamCode           string               `protobuf:"bytes,5,opt,name=stream_code,json=streamCode,proto3" json:"stream_code,omitempty"`
	OfferId              int32                `protobuf:"varint,6,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	UserId               int32                `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientUuid           string               `protobuf:"bytes,8,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
	Status               int32                `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	Sum                  float32              `protobuf:"fixed32,10,opt,name=sum,proto3" json:"sum,omitempty"`
	Payment              float32              `protobuf:"fixed32,11,opt,name=payment,proto3" json:"payment,omitempty"`
	Currency             string               `protobuf:"bytes,12,opt,name=currency,proto3" json:"currency,omitempty"`
	GeoCodes             []string             `protobuf:"bytes,13,rep,name=geo_codes,json=geoCodes,proto3" json:"geo_codes,omitempty"`
	Sub1                 string               `protobuf:"bytes,14,opt,name=sub1,proto3" json:"sub1,omitempty"`
	Sub2                 string               `protobuf:"bytes,15,opt,name=sub2,proto3" json:"sub2,omitempty"`
	Sub3                 string               `protobuf:"bytes,16,opt,name=sub3,proto3" json:"sub3,omitempty"`
	Sub4                 string               `protobuf:"bytes,17,opt,name=sub4,proto3" json:"sub4,omitempty"`
	Sub5                 string               `protobuf:"bytes,18,opt,name=sub5,proto3" json:"sub5,omitempty"`
	ErrorReason          string               `protobuf:"bytes,19,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	Pills                int32                `protobuf:"varint,20,opt,name=pills,proto3" json:"pills,omitempty"`
	Comment              string               `protobuf:"bytes,21,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CreateOrderRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CreateOrderRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CreateOrderRequest) GetVisitUuid() string {
	if m != nil {
		return m.VisitUuid
	}
	return ""
}

func (m *CreateOrderRequest) GetStreamCode() string {
	if m != nil {
		return m.StreamCode
	}
	return ""
}

func (m *CreateOrderRequest) GetOfferId() int32 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

func (m *CreateOrderRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateOrderRequest) GetClientUuid() string {
	if m != nil {
		return m.ClientUuid
	}
	return ""
}

func (m *CreateOrderRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateOrderRequest) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *CreateOrderRequest) GetPayment() float32 {
	if m != nil {
		return m.Payment
	}
	return 0
}

func (m *CreateOrderRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *CreateOrderRequest) GetGeoCodes() []string {
	if m != nil {
		return m.GeoCodes
	}
	return nil
}

func (m *CreateOrderRequest) GetSub1() string {
	if m != nil {
		return m.Sub1
	}
	return ""
}

func (m *CreateOrderRequest) GetSub2() string {
	if m != nil {
		return m.Sub2
	}
	return ""
}

func (m *CreateOrderRequest) GetSub3() string {
	if m != nil {
		return m.Sub3
	}
	return ""
}

func (m *CreateOrderRequest) GetSub4() string {
	if m != nil {
		return m.Sub4
	}
	return ""
}

func (m *CreateOrderRequest) GetSub5() string {
	if m != nil {
		return m.Sub5
	}
	return ""
}

func (m *CreateOrderRequest) GetErrorReason() string {
	if m != nil {
		return m.ErrorReason
	}
	return ""
}

func (m *CreateOrderRequest) GetPills() int32 {
	if m != nil {
		return m.Pills
	}
	return 0
}

func (m *CreateOrderRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type Order struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Type                 int32                `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	VisitUuid            string               `protobuf:"bytes,4,opt,name=visit_uuid,json=visitUuid,proto3" json:"visit_uuid,omitempty"`
	StreamCode           string               `protobuf:"bytes,5,opt,name=stream_code,json=streamCode,proto3" json:"stream_code,omitempty"`
	OfferId              int32                `protobuf:"varint,6,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	UserId               int32                `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientUuid           string               `protobuf:"bytes,8,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
	Status               int32                `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	Sum                  float32              `protobuf:"fixed32,10,opt,name=sum,proto3" json:"sum,omitempty"`
	Payment              float32              `protobuf:"fixed32,11,opt,name=payment,proto3" json:"payment,omitempty"`
	Currency             string               `protobuf:"bytes,12,opt,name=currency,proto3" json:"currency,omitempty"`
	GeoCodes             []string             `protobuf:"bytes,13,rep,name=geo_codes,json=geoCodes,proto3" json:"geo_codes,omitempty"`
	Sub1                 string               `protobuf:"bytes,14,opt,name=sub1,proto3" json:"sub1,omitempty"`
	Sub2                 string               `protobuf:"bytes,15,opt,name=sub2,proto3" json:"sub2,omitempty"`
	Sub3                 string               `protobuf:"bytes,16,opt,name=sub3,proto3" json:"sub3,omitempty"`
	Sub4                 string               `protobuf:"bytes,17,opt,name=sub4,proto3" json:"sub4,omitempty"`
	Sub5                 string               `protobuf:"bytes,18,opt,name=sub5,proto3" json:"sub5,omitempty"`
	ErrorReason          string               `protobuf:"bytes,19,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	Pills                int32                `protobuf:"varint,20,opt,name=pills,proto3" json:"pills,omitempty"`
	Comment              string               `protobuf:"bytes,21,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Order) GetVisitUuid() string {
	if m != nil {
		return m.VisitUuid
	}
	return ""
}

func (m *Order) GetStreamCode() string {
	if m != nil {
		return m.StreamCode
	}
	return ""
}

func (m *Order) GetOfferId() int32 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

func (m *Order) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Order) GetClientUuid() string {
	if m != nil {
		return m.ClientUuid
	}
	return ""
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *Order) GetPayment() float32 {
	if m != nil {
		return m.Payment
	}
	return 0
}

func (m *Order) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Order) GetGeoCodes() []string {
	if m != nil {
		return m.GeoCodes
	}
	return nil
}

func (m *Order) GetSub1() string {
	if m != nil {
		return m.Sub1
	}
	return ""
}

func (m *Order) GetSub2() string {
	if m != nil {
		return m.Sub2
	}
	return ""
}

func (m *Order) GetSub3() string {
	if m != nil {
		return m.Sub3
	}
	return ""
}

func (m *Order) GetSub4() string {
	if m != nil {
		return m.Sub4
	}
	return ""
}

func (m *Order) GetSub5() string {
	if m != nil {
		return m.Sub5
	}
	return ""
}

func (m *Order) GetErrorReason() string {
	if m != nil {
		return m.ErrorReason
	}
	return ""
}

func (m *Order) GetPills() int32 {
	if m != nil {
		return m.Pills
	}
	return 0
}

func (m *Order) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type ListOrdersRequest struct {
	Limit                int32                `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32                `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	DateStart            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date_start,json=dateStart,proto3" json:"date_start,omitempty"`
	DateEnd              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date_end,json=dateEnd,proto3" json:"date_end,omitempty"`
	Type                 int32                `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	UserId               int32                `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uuid                 string               `protobuf:"bytes,7,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OfferId              int32                `protobuf:"varint,8,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListOrdersRequest) Reset()         { *m = ListOrdersRequest{} }
func (m *ListOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrdersRequest) ProtoMessage()    {}
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *ListOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrdersRequest.Unmarshal(m, b)
}
func (m *ListOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrdersRequest.Marshal(b, m, deterministic)
}
func (m *ListOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrdersRequest.Merge(m, src)
}
func (m *ListOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrdersRequest.Size(m)
}
func (m *ListOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrdersRequest proto.InternalMessageInfo

func (m *ListOrdersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListOrdersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListOrdersRequest) GetDateStart() *timestamp.Timestamp {
	if m != nil {
		return m.DateStart
	}
	return nil
}

func (m *ListOrdersRequest) GetDateEnd() *timestamp.Timestamp {
	if m != nil {
		return m.DateEnd
	}
	return nil
}

func (m *ListOrdersRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ListOrdersRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListOrdersRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ListOrdersRequest) GetOfferId() int32 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

type ListOrdersResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrdersResponse) Reset()         { *m = ListOrdersResponse{} }
func (m *ListOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*ListOrdersResponse) ProtoMessage()    {}
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *ListOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrdersResponse.Unmarshal(m, b)
}
func (m *ListOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrdersResponse.Marshal(b, m, deterministic)
}
func (m *ListOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrdersResponse.Merge(m, src)
}
func (m *ListOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_ListOrdersResponse.Size(m)
}
func (m *ListOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrdersResponse proto.InternalMessageInfo

func (m *ListOrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *ListOrdersResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ListUserPaymentsRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	UserId               []int32  `protobuf:"varint,3,rep,packed,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency             []string `protobuf:"bytes,4,rep,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserPaymentsRequest) Reset()         { *m = ListUserPaymentsRequest{} }
func (m *ListUserPaymentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserPaymentsRequest) ProtoMessage()    {}
func (*ListUserPaymentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *ListUserPaymentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserPaymentsRequest.Unmarshal(m, b)
}
func (m *ListUserPaymentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserPaymentsRequest.Marshal(b, m, deterministic)
}
func (m *ListUserPaymentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserPaymentsRequest.Merge(m, src)
}
func (m *ListUserPaymentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserPaymentsRequest.Size(m)
}
func (m *ListUserPaymentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserPaymentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserPaymentsRequest proto.InternalMessageInfo

func (m *ListUserPaymentsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListUserPaymentsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListUserPaymentsRequest) GetUserId() []int32 {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *ListUserPaymentsRequest) GetCurrency() []string {
	if m != nil {
		return m.Currency
	}
	return nil
}

type UserPayment struct {
	UserId               int32       `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency             string      `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Sum                  float32     `protobuf:"fixed32,3,opt,name=sum,proto3" json:"sum,omitempty"`
	Type                 PaymentType `protobuf:"varint,4,opt,name=type,proto3,enum=order.PaymentType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserPayment) Reset()         { *m = UserPayment{} }
func (m *UserPayment) String() string { return proto.CompactTextString(m) }
func (*UserPayment) ProtoMessage()    {}
func (*UserPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *UserPayment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPayment.Unmarshal(m, b)
}
func (m *UserPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPayment.Marshal(b, m, deterministic)
}
func (m *UserPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPayment.Merge(m, src)
}
func (m *UserPayment) XXX_Size() int {
	return xxx_messageInfo_UserPayment.Size(m)
}
func (m *UserPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPayment.DiscardUnknown(m)
}

var xxx_messageInfo_UserPayment proto.InternalMessageInfo

func (m *UserPayment) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserPayment) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *UserPayment) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *UserPayment) GetType() PaymentType {
	if m != nil {
		return m.Type
	}
	return PaymentType_PaymentDefault
}

type ListUserPaymentsResponse struct {
	UserPayments         []*UserPayment `protobuf:"bytes,1,rep,name=user_payments,json=userPayments,proto3" json:"user_payments,omitempty"`
	Total                int32          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListUserPaymentsResponse) Reset()         { *m = ListUserPaymentsResponse{} }
func (m *ListUserPaymentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserPaymentsResponse) ProtoMessage()    {}
func (*ListUserPaymentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *ListUserPaymentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserPaymentsResponse.Unmarshal(m, b)
}
func (m *ListUserPaymentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserPaymentsResponse.Marshal(b, m, deterministic)
}
func (m *ListUserPaymentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserPaymentsResponse.Merge(m, src)
}
func (m *ListUserPaymentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserPaymentsResponse.Size(m)
}
func (m *ListUserPaymentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserPaymentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserPaymentsResponse proto.InternalMessageInfo

func (m *ListUserPaymentsResponse) GetUserPayments() []*UserPayment {
	if m != nil {
		return m.UserPayments
	}
	return nil
}

func (m *ListUserPaymentsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterEnum("order.PaymentType", PaymentType_name, PaymentType_value)
	proto.RegisterType((*CreateOrderRequest)(nil), "order.CreateOrderRequest")
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*ListOrdersRequest)(nil), "order.ListOrdersRequest")
	proto.RegisterType((*ListOrdersResponse)(nil), "order.ListOrdersResponse")
	proto.RegisterType((*ListUserPaymentsRequest)(nil), "order.ListUserPaymentsRequest")
	proto.RegisterType((*UserPayment)(nil), "order.UserPayment")
	proto.RegisterType((*ListUserPaymentsResponse)(nil), "order.ListUserPaymentsResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 735 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0xdd, 0x6e, 0x13, 0x3b,
	0x10, 0x3e, 0x9b, 0x64, 0xf3, 0x33, 0x9b, 0xb6, 0xa9, 0x4f, 0xcf, 0xa9, 0x1b, 0x04, 0x0d, 0x11,
	0x42, 0x11, 0x17, 0xa9, 0x48, 0x5b, 0x10, 0x97, 0x55, 0x41, 0xa2, 0x12, 0x12, 0xd5, 0xb6, 0xbd,
	0x8e, 0xb6, 0x59, 0x27, 0x5a, 0x69, 0x13, 0x2f, 0xb6, 0xb7, 0x52, 0xa4, 0xbe, 0x03, 0x0f, 0xc3,
	0x0b, 0xf0, 0x24, 0x3c, 0x0b, 0xf2, 0xd8, 0xbb, 0x75, 0xfa, 0x03, 0x88, 0xeb, 0xde, 0x79, 0xbe,
	0x19, 0xcf, 0xb7, 0xf3, 0xf9, 0xb3, 0x17, 0x02, 0x2e, 0x62, 0x26, 0x86, 0x99, 0xe0, 0x8a, 0x13,
	0x1f, 0x83, 0xee, 0xee, 0x8c, 0xf3, 0x59, 0xca, 0xf6, 0x10, 0xbc, 0xcc, 0xa7, 0x7b, 0x2a, 0x99,
	0x33, 0xa9, 0xa2, 0x79, 0x66, 0xea, 0xfa, 0xdf, 0x6b, 0x40, 0x8e, 0x05, 0x8b, 0x14, 0xfb, 0xac,
	0x37, 0x84, 0xec, 0x4b, 0xce, 0xa4, 0x22, 0x04, 0x6a, 0x79, 0x9e, 0xc4, 0xd4, 0xeb, 0x79, 0x83,
	0x56, 0x88, 0x6b, 0xf2, 0x0e, 0x60, 0x82, 0x95, 0xf1, 0x38, 0x52, 0xb4, 0xd2, 0xf3, 0x06, 0xc1,
	0xa8, 0x3b, 0x34, 0x04, 0xc3, 0x82, 0x60, 0x78, 0x5e, 0x10, 0x84, 0x2d, 0x5b, 0x7d, 0x84, 0xed,
	0xd4, 0x32, 0x63, 0xb4, 0xda, 0xf3, 0x06, 0x7e, 0x88, 0x6b, 0xf2, 0x14, 0xe0, 0x2a, 0x91, 0x89,
	0x1a, 0x23, 0x51, 0x0d, 0x89, 0x5a, 0x88, 0x5c, 0x68, 0xb6, 0x5d, 0x08, 0xa4, 0x12, 0x2c, 0x9a,
	0x8f, 0x27, 0x3c, 0x66, 0xd4, 0xc7, 0x3c, 0x18, 0xe8, 0x98, 0xc7, 0x8c, 0xec, 0x40, 0x93, 0x4f,
	0xa7, 0x4c, 0x8c, 0x93, 0x98, 0xd6, 0xb1, 0x6f, 0x03, 0xe3, 0x93, 0x98, 0x6c, 0x43, 0x23, 0x97,
	0x26, 0xd3, 0xc0, 0x4c, 0x5d, 0x87, 0x27, 0xd8, 0x74, 0x92, 0x26, 0x6c, 0x61, 0x49, 0x9b, 0xa6,
	0xa9, 0x81, 0x90, 0xf5, 0x7f, 0xa8, 0x4b, 0x15, 0xa9, 0x5c, 0xd2, 0x96, 0xd9, 0x68, 0x22, 0xd2,
	0x81, 0xaa, 0xcc, 0xe7, 0x14, 0x7a, 0xde, 0xa0, 0x12, 0xea, 0x25, 0xa1, 0xd0, 0xc8, 0xa2, 0xe5,
	0x9c, 0x2d, 0x14, 0x0d, 0x10, 0x2d, 0x42, 0xd2, 0x85, 0xe6, 0x24, 0x17, 0x82, 0x2d, 0x26, 0x4b,
	0xda, 0x46, 0x86, 0x32, 0x26, 0x4f, 0xa0, 0x35, 0x63, 0x1c, 0x47, 0x92, 0x74, 0xad, 0x57, 0xd5,
	0xc9, 0x19, 0xe3, 0x7a, 0x20, 0xa9, 0x55, 0x92, 0xf9, 0xe5, 0x6b, 0xba, 0x6e, 0x44, 0xd7, 0x6b,
	0x8b, 0x8d, 0xe8, 0x46, 0x89, 0x8d, 0x2c, 0xb6, 0x4f, 0x3b, 0x25, 0xb6, 0x6f, 0xb1, 0x03, 0xba,
	0x59, 0x62, 0x07, 0x16, 0x3b, 0xa4, 0xa4, 0xc4, 0x0e, 0xc9, 0x73, 0x68, 0x33, 0x21, 0xb8, 0x18,
	0x0b, 0x16, 0x49, 0xbe, 0xa0, 0xff, 0x62, 0x2e, 0x40, 0x2c, 0x44, 0x88, 0x6c, 0x81, 0x9f, 0x25,
	0x69, 0x2a, 0xe9, 0x16, 0x4a, 0x60, 0x02, 0x3d, 0xef, 0x84, 0xcf, 0x71, 0xde, 0xff, 0x70, 0x4f,
	0x11, 0xf6, 0xbf, 0xd5, 0xc0, 0x47, 0xf3, 0x3c, 0xba, 0xe6, 0xd1, 0x35, 0x7f, 0xec, 0x9a, 0xaf,
	0x15, 0xd8, 0xfc, 0x94, 0x48, 0x85, 0xce, 0x91, 0xc5, 0xbb, 0xb3, 0x05, 0x7e, 0x9a, 0xcc, 0x13,
	0x85, 0x16, 0xf2, 0x43, 0x13, 0x68, 0x7d, 0xf9, 0x74, 0x2a, 0x99, 0xf1, 0x8f, 0x1f, 0xda, 0x48,
	0x7b, 0x2b, 0x8e, 0x14, 0x1b, 0x4b, 0x15, 0x09, 0x85, 0x36, 0xf9, 0x8d, 0xb7, 0x74, 0xf5, 0x99,
	0x2e, 0x26, 0x87, 0xd0, 0xc4, 0xad, 0x6c, 0x61, 0x5c, 0xf4, 0xeb, 0x8d, 0x0d, 0x5d, 0xfb, 0x61,
	0x11, 0x97, 0x96, 0xf4, 0x1d, 0x4b, 0x3a, 0xbe, 0xa9, 0xaf, 0xf8, 0xa6, 0xb8, 0x0e, 0x0d, 0xe7,
	0x3a, 0xb8, 0xfe, 0x6b, 0xae, 0xf8, 0xaf, 0x7f, 0x0a, 0xc4, 0x15, 0x44, 0x66, 0x7c, 0x21, 0x19,
	0x79, 0x01, 0x75, 0x7c, 0xca, 0x25, 0xf5, 0x7a, 0xd5, 0x41, 0x30, 0x6a, 0x0f, 0xcd, 0x33, 0x6f,
	0x9e, 0x6b, 0x9b, 0xd3, 0xba, 0x29, 0xae, 0xa2, 0xd4, 0x0a, 0x64, 0x82, 0xfe, 0x35, 0x6c, 0xeb,
	0x8e, 0x17, 0x92, 0x89, 0x53, 0x63, 0xb3, 0xbf, 0x14, 0xda, 0x19, 0xb1, 0xda, 0xab, 0x3a, 0x23,
	0xba, 0xae, 0xad, 0x19, 0x63, 0x16, 0x71, 0xff, 0x1a, 0x02, 0x87, 0xd9, 0xed, 0xe1, 0xad, 0xc8,
	0xe4, 0xf6, 0xa8, 0xdc, 0x72, 0xbe, 0xbd, 0x41, 0xd5, 0x9b, 0x1b, 0xf4, 0xd2, 0x9e, 0x80, 0x3e,
	0xb4, 0xf5, 0x11, 0xb1, 0x6a, 0x58, 0x92, 0xf3, 0x65, 0xc6, 0xcc, 0xa9, 0xf4, 0x13, 0xa0, 0x77,
	0x67, 0xb7, 0x9a, 0xbe, 0x85, 0x35, 0xfc, 0x14, 0x7b, 0xf7, 0x0a, 0x69, 0x8b, 0x66, 0xce, 0x9e,
	0xb0, 0x9d, 0x3b, 0x0d, 0xee, 0x97, 0xf9, 0xd5, 0x08, 0x02, 0x87, 0x9f, 0x10, 0x58, 0xb7, 0xe1,
	0x7b, 0x36, 0x8d, 0xf2, 0x54, 0x75, 0xfe, 0x21, 0x1b, 0x65, 0xc9, 0x47, 0x9e, 0xc6, 0x1d, 0x6f,
	0xf4, 0xc3, 0x83, 0x36, 0x1e, 0xe1, 0x19, 0x13, 0x57, 0xc9, 0x84, 0x91, 0x33, 0xe8, 0xdc, 0xfe,
	0x5e, 0xf2, 0xcc, 0x7e, 0xd0, 0x03, 0x87, 0xd8, 0xdd, 0x7d, 0x30, 0x6f, 0x07, 0x7d, 0x03, 0x81,
	0xf3, 0x73, 0x27, 0x3b, 0xb6, 0xfe, 0xee, 0x0f, 0xbf, 0xbb, 0x62, 0x2b, 0x72, 0x04, 0x70, 0x63,
	0x45, 0x42, 0x1d, 0x9a, 0x95, 0xeb, 0xda, 0xdd, 0xb9, 0x27, 0x63, 0xa8, 0x2f, 0xeb, 0x78, 0x8d,
	0xf6, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x03, 0x06, 0x2d, 0xbe, 0x96, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	ListUserPayments(ctx context.Context, in *ListUserPaymentsRequest, opts ...grpc.CallOption) (*ListUserPaymentsResponse, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error)
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) ListUserPayments(ctx context.Context, in *ListUserPaymentsRequest, opts ...grpc.CallOption) (*ListUserPaymentsResponse, error) {
	out := new(ListUserPaymentsResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/ListUserPayments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/order.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/ListOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	ListUserPayments(context.Context, *ListUserPaymentsRequest) (*ListUserPaymentsResponse, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*Order, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) ListUserPayments(ctx context.Context, req *ListUserPaymentsRequest) (*ListUserPaymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserPayments not implemented")
}
func (*UnimplementedOrderServiceServer) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedOrderServiceServer) ListOrders(ctx context.Context, req *ListOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_ListUserPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListUserPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/ListUserPayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListUserPayments(ctx, req.(*ListUserPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/ListOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListOrders(ctx, req.(*ListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUserPayments",
			Handler:    _OrderService_ListUserPayments_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _OrderService_ListOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
