// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

/*
Package order is a generated protocol buffer package.

It is generated from these files:
	order.proto

It has these top-level messages:
	CreateOrderRequest
	Order
	ListOrdersRequest
	ListOrdersResponse
	ListUserPaymentsRequest
	UserPayment
	ListUserPaymentsResponse
*/
package order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateOrderRequest struct {
	Uuid        string                     `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	CreatedAt   *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Type        int32                      `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	VisitUuid   string                     `protobuf:"bytes,4,opt,name=visit_uuid,json=visitUuid" json:"visit_uuid,omitempty"`
	StreamCode  string                     `protobuf:"bytes,5,opt,name=stream_code,json=streamCode" json:"stream_code,omitempty"`
	OfferId     int32                      `protobuf:"varint,6,opt,name=offer_id,json=offerId" json:"offer_id,omitempty"`
	UserId      int32                      `protobuf:"varint,7,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ClientUuid  string                     `protobuf:"bytes,8,opt,name=client_uuid,json=clientUuid" json:"client_uuid,omitempty"`
	Status      int32                      `protobuf:"varint,9,opt,name=status" json:"status,omitempty"`
	Sum         float32                    `protobuf:"fixed32,10,opt,name=sum" json:"sum,omitempty"`
	Payment     float32                    `protobuf:"fixed32,11,opt,name=payment" json:"payment,omitempty"`
	Currency    string                     `protobuf:"bytes,12,opt,name=currency" json:"currency,omitempty"`
	GeoCodes    []string                   `protobuf:"bytes,13,rep,name=geo_codes,json=geoCodes" json:"geo_codes,omitempty"`
	Sub1        string                     `protobuf:"bytes,14,opt,name=sub1" json:"sub1,omitempty"`
	Sub2        string                     `protobuf:"bytes,15,opt,name=sub2" json:"sub2,omitempty"`
	Sub3        string                     `protobuf:"bytes,16,opt,name=sub3" json:"sub3,omitempty"`
	Sub4        string                     `protobuf:"bytes,17,opt,name=sub4" json:"sub4,omitempty"`
	Sub5        string                     `protobuf:"bytes,18,opt,name=sub5" json:"sub5,omitempty"`
	ErrorReason string                     `protobuf:"bytes,19,opt,name=error_reason,json=errorReason" json:"error_reason,omitempty"`
	Pills       int32                      `protobuf:"varint,20,opt,name=pills" json:"pills,omitempty"`
	Comment     string                     `protobuf:"bytes,21,opt,name=comment" json:"comment,omitempty"`
}

func (m *CreateOrderRequest) Reset()                    { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()               {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateOrderRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CreateOrderRequest) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *CreateOrderRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CreateOrderRequest) GetVisitUuid() string {
	if m != nil {
		return m.VisitUuid
	}
	return ""
}

func (m *CreateOrderRequest) GetStreamCode() string {
	if m != nil {
		return m.StreamCode
	}
	return ""
}

func (m *CreateOrderRequest) GetOfferId() int32 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

func (m *CreateOrderRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateOrderRequest) GetClientUuid() string {
	if m != nil {
		return m.ClientUuid
	}
	return ""
}

func (m *CreateOrderRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateOrderRequest) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *CreateOrderRequest) GetPayment() float32 {
	if m != nil {
		return m.Payment
	}
	return 0
}

func (m *CreateOrderRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *CreateOrderRequest) GetGeoCodes() []string {
	if m != nil {
		return m.GeoCodes
	}
	return nil
}

func (m *CreateOrderRequest) GetSub1() string {
	if m != nil {
		return m.Sub1
	}
	return ""
}

func (m *CreateOrderRequest) GetSub2() string {
	if m != nil {
		return m.Sub2
	}
	return ""
}

func (m *CreateOrderRequest) GetSub3() string {
	if m != nil {
		return m.Sub3
	}
	return ""
}

func (m *CreateOrderRequest) GetSub4() string {
	if m != nil {
		return m.Sub4
	}
	return ""
}

func (m *CreateOrderRequest) GetSub5() string {
	if m != nil {
		return m.Sub5
	}
	return ""
}

func (m *CreateOrderRequest) GetErrorReason() string {
	if m != nil {
		return m.ErrorReason
	}
	return ""
}

func (m *CreateOrderRequest) GetPills() int32 {
	if m != nil {
		return m.Pills
	}
	return 0
}

func (m *CreateOrderRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type Order struct {
	Uuid        string                     `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	CreatedAt   *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Type        int32                      `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	VisitUuid   string                     `protobuf:"bytes,4,opt,name=visit_uuid,json=visitUuid" json:"visit_uuid,omitempty"`
	StreamCode  string                     `protobuf:"bytes,5,opt,name=stream_code,json=streamCode" json:"stream_code,omitempty"`
	OfferId     int32                      `protobuf:"varint,6,opt,name=offer_id,json=offerId" json:"offer_id,omitempty"`
	UserId      int32                      `protobuf:"varint,7,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ClientUuid  string                     `protobuf:"bytes,8,opt,name=client_uuid,json=clientUuid" json:"client_uuid,omitempty"`
	Status      int32                      `protobuf:"varint,9,opt,name=status" json:"status,omitempty"`
	Sum         float32                    `protobuf:"fixed32,10,opt,name=sum" json:"sum,omitempty"`
	Payment     float32                    `protobuf:"fixed32,11,opt,name=payment" json:"payment,omitempty"`
	Currency    string                     `protobuf:"bytes,12,opt,name=currency" json:"currency,omitempty"`
	GeoCodes    []string                   `protobuf:"bytes,13,rep,name=geo_codes,json=geoCodes" json:"geo_codes,omitempty"`
	Sub1        string                     `protobuf:"bytes,14,opt,name=sub1" json:"sub1,omitempty"`
	Sub2        string                     `protobuf:"bytes,15,opt,name=sub2" json:"sub2,omitempty"`
	Sub3        string                     `protobuf:"bytes,16,opt,name=sub3" json:"sub3,omitempty"`
	Sub4        string                     `protobuf:"bytes,17,opt,name=sub4" json:"sub4,omitempty"`
	Sub5        string                     `protobuf:"bytes,18,opt,name=sub5" json:"sub5,omitempty"`
	ErrorReason string                     `protobuf:"bytes,19,opt,name=error_reason,json=errorReason" json:"error_reason,omitempty"`
	Pills       int32                      `protobuf:"varint,20,opt,name=pills" json:"pills,omitempty"`
	Comment     string                     `protobuf:"bytes,21,opt,name=comment" json:"comment,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Order) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Order) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Order) GetVisitUuid() string {
	if m != nil {
		return m.VisitUuid
	}
	return ""
}

func (m *Order) GetStreamCode() string {
	if m != nil {
		return m.StreamCode
	}
	return ""
}

func (m *Order) GetOfferId() int32 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

func (m *Order) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Order) GetClientUuid() string {
	if m != nil {
		return m.ClientUuid
	}
	return ""
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *Order) GetPayment() float32 {
	if m != nil {
		return m.Payment
	}
	return 0
}

func (m *Order) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Order) GetGeoCodes() []string {
	if m != nil {
		return m.GeoCodes
	}
	return nil
}

func (m *Order) GetSub1() string {
	if m != nil {
		return m.Sub1
	}
	return ""
}

func (m *Order) GetSub2() string {
	if m != nil {
		return m.Sub2
	}
	return ""
}

func (m *Order) GetSub3() string {
	if m != nil {
		return m.Sub3
	}
	return ""
}

func (m *Order) GetSub4() string {
	if m != nil {
		return m.Sub4
	}
	return ""
}

func (m *Order) GetSub5() string {
	if m != nil {
		return m.Sub5
	}
	return ""
}

func (m *Order) GetErrorReason() string {
	if m != nil {
		return m.ErrorReason
	}
	return ""
}

func (m *Order) GetPills() int32 {
	if m != nil {
		return m.Pills
	}
	return 0
}

func (m *Order) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type ListOrdersRequest struct {
	Limit     int32                      `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset    int32                      `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	DateStart *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=date_start,json=dateStart" json:"date_start,omitempty"`
	DateEnd   *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=date_end,json=dateEnd" json:"date_end,omitempty"`
	Type      int32                      `protobuf:"varint,5,opt,name=type" json:"type,omitempty"`
	UserId    int32                      `protobuf:"varint,6,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Uuid      string                     `protobuf:"bytes,7,opt,name=uuid" json:"uuid,omitempty"`
	OfferId   int32                      `protobuf:"varint,8,opt,name=offer_id,json=offerId" json:"offer_id,omitempty"`
}

func (m *ListOrdersRequest) Reset()                    { *m = ListOrdersRequest{} }
func (m *ListOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListOrdersRequest) ProtoMessage()               {}
func (*ListOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListOrdersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListOrdersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListOrdersRequest) GetDateStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.DateStart
	}
	return nil
}

func (m *ListOrdersRequest) GetDateEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.DateEnd
	}
	return nil
}

func (m *ListOrdersRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ListOrdersRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListOrdersRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ListOrdersRequest) GetOfferId() int32 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

type ListOrdersResponse struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
	Total  int32    `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (m *ListOrdersResponse) Reset()                    { *m = ListOrdersResponse{} }
func (m *ListOrdersResponse) String() string            { return proto.CompactTextString(m) }
func (*ListOrdersResponse) ProtoMessage()               {}
func (*ListOrdersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListOrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *ListOrdersResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ListUserPaymentsRequest struct {
	Limit    int32    `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset   int32    `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	UserId   []int32  `protobuf:"varint,3,rep,packed,name=user_id,json=userId" json:"user_id,omitempty"`
	Currency []string `protobuf:"bytes,4,rep,name=currency" json:"currency,omitempty"`
}

func (m *ListUserPaymentsRequest) Reset()                    { *m = ListUserPaymentsRequest{} }
func (m *ListUserPaymentsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListUserPaymentsRequest) ProtoMessage()               {}
func (*ListUserPaymentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListUserPaymentsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListUserPaymentsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListUserPaymentsRequest) GetUserId() []int32 {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *ListUserPaymentsRequest) GetCurrency() []string {
	if m != nil {
		return m.Currency
	}
	return nil
}

type UserPayment struct {
	UserId   int32   `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Currency string  `protobuf:"bytes,2,opt,name=currency" json:"currency,omitempty"`
	Sum      float32 `protobuf:"fixed32,3,opt,name=sum" json:"sum,omitempty"`
}

func (m *UserPayment) Reset()                    { *m = UserPayment{} }
func (m *UserPayment) String() string            { return proto.CompactTextString(m) }
func (*UserPayment) ProtoMessage()               {}
func (*UserPayment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserPayment) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserPayment) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *UserPayment) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

type ListUserPaymentsResponse struct {
	UserPayments []*UserPayment `protobuf:"bytes,1,rep,name=user_payments,json=userPayments" json:"user_payments,omitempty"`
	Total        int32          `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (m *ListUserPaymentsResponse) Reset()                    { *m = ListUserPaymentsResponse{} }
func (m *ListUserPaymentsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListUserPaymentsResponse) ProtoMessage()               {}
func (*ListUserPaymentsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ListUserPaymentsResponse) GetUserPayments() []*UserPayment {
	if m != nil {
		return m.UserPayments
	}
	return nil
}

func (m *ListUserPaymentsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "order.CreateOrderRequest")
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*ListOrdersRequest)(nil), "order.ListOrdersRequest")
	proto.RegisterType((*ListOrdersResponse)(nil), "order.ListOrdersResponse")
	proto.RegisterType((*ListUserPaymentsRequest)(nil), "order.ListUserPaymentsRequest")
	proto.RegisterType((*UserPayment)(nil), "order.UserPayment")
	proto.RegisterType((*ListUserPaymentsResponse)(nil), "order.ListUserPaymentsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OrderService service

type OrderServiceClient interface {
	ListUserPayments(ctx context.Context, in *ListUserPaymentsRequest, opts ...grpc.CallOption) (*ListUserPaymentsResponse, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error)
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) ListUserPayments(ctx context.Context, in *ListUserPaymentsRequest, opts ...grpc.CallOption) (*ListUserPaymentsResponse, error) {
	out := new(ListUserPaymentsResponse)
	err := grpc.Invoke(ctx, "/order.OrderService/ListUserPayments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := grpc.Invoke(ctx, "/order.OrderService/CreateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	out := new(ListOrdersResponse)
	err := grpc.Invoke(ctx, "/order.OrderService/ListOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderService service

type OrderServiceServer interface {
	ListUserPayments(context.Context, *ListUserPaymentsRequest) (*ListUserPaymentsResponse, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*Order, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_ListUserPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListUserPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/ListUserPayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListUserPayments(ctx, req.(*ListUserPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/ListOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListOrders(ctx, req.(*ListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUserPayments",
			Handler:    _OrderService_ListUserPayments_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _OrderService_ListOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}

func init() { proto.RegisterFile("order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 688 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x95, 0xe3, 0x38, 0x3f, 0xe3, 0xf4, 0xfb, 0xda, 0xa5, 0xd0, 0x6d, 0x10, 0xd4, 0x44, 0x5c,
	0xe4, 0x2a, 0x15, 0x69, 0x0b, 0xe2, 0xb2, 0xaa, 0xb8, 0xa8, 0x84, 0x44, 0xe5, 0xb6, 0xd7, 0x91,
	0x6b, 0x6f, 0x22, 0x4b, 0xb1, 0x37, 0xec, 0xae, 0x2b, 0x55, 0xe2, 0x1d, 0x78, 0x18, 0x5e, 0x80,
	0x27, 0xe1, 0x59, 0xd0, 0xce, 0xae, 0xcd, 0xa6, 0x3f, 0x80, 0xb8, 0xee, 0xdd, 0xce, 0x99, 0xd9,
	0x39, 0x99, 0x93, 0x33, 0x6b, 0x08, 0xb9, 0xc8, 0x98, 0x98, 0xac, 0x04, 0x57, 0x9c, 0x04, 0x18,
	0x0c, 0xf7, 0x16, 0x9c, 0x2f, 0x96, 0x6c, 0x1f, 0xc1, 0xab, 0x6a, 0xbe, 0xaf, 0xf2, 0x82, 0x49,
	0x95, 0x14, 0x2b, 0x53, 0x37, 0xfa, 0xde, 0x06, 0x72, 0x22, 0x58, 0xa2, 0xd8, 0x27, 0x7d, 0x21,
	0x66, 0x9f, 0x2b, 0x26, 0x15, 0x21, 0xd0, 0xae, 0xaa, 0x3c, 0xa3, 0x5e, 0xe4, 0x8d, 0xfb, 0x31,
	0x9e, 0xc9, 0x7b, 0x80, 0x14, 0x2b, 0xb3, 0x59, 0xa2, 0x68, 0x2b, 0xf2, 0xc6, 0xe1, 0x74, 0x38,
	0x31, 0x04, 0x93, 0x9a, 0x60, 0x72, 0x51, 0x13, 0xc4, 0x7d, 0x5b, 0x7d, 0x8c, 0xed, 0xd4, 0xcd,
	0x8a, 0x51, 0x3f, 0xf2, 0xc6, 0x41, 0x8c, 0x67, 0xf2, 0x02, 0xe0, 0x3a, 0x97, 0xb9, 0x9a, 0x21,
	0x51, 0x1b, 0x89, 0xfa, 0x88, 0x5c, 0x6a, 0xb6, 0x3d, 0x08, 0xa5, 0x12, 0x2c, 0x29, 0x66, 0x29,
	0xcf, 0x18, 0x0d, 0x30, 0x0f, 0x06, 0x3a, 0xe1, 0x19, 0x23, 0xbb, 0xd0, 0xe3, 0xf3, 0x39, 0x13,
	0xb3, 0x3c, 0xa3, 0x1d, 0xec, 0xdb, 0xc5, 0xf8, 0x34, 0x23, 0x3b, 0xd0, 0xad, 0xa4, 0xc9, 0x74,
	0x31, 0xd3, 0xd1, 0xe1, 0x29, 0x36, 0x4d, 0x97, 0x39, 0x2b, 0x2d, 0x69, 0xcf, 0x34, 0x35, 0x10,
	0xb2, 0x3e, 0x83, 0x8e, 0x54, 0x89, 0xaa, 0x24, 0xed, 0x9b, 0x8b, 0x26, 0x22, 0x9b, 0xe0, 0xcb,
	0xaa, 0xa0, 0x10, 0x79, 0xe3, 0x56, 0xac, 0x8f, 0x84, 0x42, 0x77, 0x95, 0xdc, 0x14, 0xac, 0x54,
	0x34, 0x44, 0xb4, 0x0e, 0xc9, 0x10, 0x7a, 0x69, 0x25, 0x04, 0x2b, 0xd3, 0x1b, 0x3a, 0x40, 0x86,
	0x26, 0x26, 0xcf, 0xa1, 0xbf, 0x60, 0x1c, 0x47, 0x92, 0x74, 0x23, 0xf2, 0x75, 0x72, 0xc1, 0xb8,
	0x1e, 0x48, 0x6a, 0x95, 0x64, 0x75, 0xf5, 0x86, 0xfe, 0x67, 0x44, 0xd7, 0x67, 0x8b, 0x4d, 0xe9,
	0xff, 0x0d, 0x36, 0xb5, 0xd8, 0x01, 0xdd, 0x6c, 0xb0, 0x03, 0x8b, 0x1d, 0xd2, 0xad, 0x06, 0x3b,
	0xb4, 0xd8, 0x11, 0x25, 0x0d, 0x76, 0x44, 0x5e, 0xc1, 0x80, 0x09, 0xc1, 0xc5, 0x4c, 0xb0, 0x44,
	0xf2, 0x92, 0x3e, 0xc1, 0x5c, 0x88, 0x58, 0x8c, 0x10, 0xd9, 0x86, 0x60, 0x95, 0x2f, 0x97, 0x92,
	0x6e, 0xa3, 0x04, 0x26, 0xd0, 0xf3, 0xa6, 0xbc, 0xc0, 0x79, 0x9f, 0xe2, 0x9d, 0x3a, 0x1c, 0x7d,
	0x6b, 0x43, 0x80, 0xe6, 0x79, 0x74, 0xcd, 0xa3, 0x6b, 0xfe, 0xda, 0x35, 0x5f, 0x5b, 0xb0, 0xf5,
	0x31, 0x97, 0x0a, 0x9d, 0x23, 0xeb, 0x77, 0x67, 0x1b, 0x82, 0x65, 0x5e, 0xe4, 0x0a, 0x2d, 0x14,
	0xc4, 0x26, 0xd0, 0xfa, 0xf2, 0xf9, 0x5c, 0x32, 0xe3, 0x9f, 0x20, 0xb6, 0x91, 0xf6, 0x56, 0x96,
	0x28, 0x36, 0x93, 0x2a, 0x11, 0x0a, 0x6d, 0xf2, 0x07, 0x6f, 0xe9, 0xea, 0x73, 0x5d, 0x4c, 0x8e,
	0xa0, 0x87, 0x57, 0x59, 0x69, 0x5c, 0xf4, 0xfb, 0x8b, 0x5d, 0x5d, 0xfb, 0xa1, 0xcc, 0x1a, 0x4b,
	0x06, 0x8e, 0x25, 0x1d, 0xdf, 0x74, 0xd6, 0x7c, 0x53, 0xaf, 0x43, 0xd7, 0x59, 0x07, 0xd7, 0x7f,
	0xbd, 0x35, 0xff, 0x8d, 0xce, 0x80, 0xb8, 0x82, 0xc8, 0x15, 0x2f, 0x25, 0x23, 0xaf, 0xa1, 0x83,
	0x4f, 0xb9, 0xa4, 0x5e, 0xe4, 0x8f, 0xc3, 0xe9, 0x60, 0x62, 0x9e, 0x79, 0xf3, 0x5c, 0xdb, 0x9c,
	0xd6, 0x4d, 0x71, 0x95, 0x2c, 0xad, 0x40, 0x26, 0x18, 0x7d, 0x81, 0x1d, 0xdd, 0xf1, 0x52, 0x32,
	0x71, 0x66, 0x6c, 0xf6, 0x8f, 0x42, 0x3b, 0x23, 0xfa, 0x91, 0xef, 0x8c, 0xe8, 0xba, 0xb6, 0x6d,
	0x8c, 0x59, 0xc7, 0xa3, 0x0b, 0x08, 0x1d, 0x66, 0xb7, 0x87, 0xb7, 0x26, 0x93, 0xdb, 0xa3, 0x75,
	0xcb, 0xf9, 0x76, 0x83, 0xfc, 0x66, 0x83, 0x46, 0x39, 0xd0, 0xbb, 0x33, 0x59, 0xad, 0xde, 0xc1,
	0x06, 0x52, 0xd8, 0x9d, 0xaa, 0x25, 0x23, 0x56, 0x32, 0xe7, 0x4e, 0x3c, 0xa8, 0x9c, 0x06, 0xf7,
	0xcb, 0x37, 0xfd, 0xe1, 0xc1, 0x00, 0x65, 0x3e, 0x67, 0xe2, 0x3a, 0x4f, 0x19, 0x39, 0x87, 0xcd,
	0xdb, 0xdc, 0xe4, 0xa5, 0x6d, 0xfe, 0x80, 0xd0, 0xc3, 0xbd, 0x07, 0xf3, 0xf6, 0x47, 0xbf, 0x85,
	0xd0, 0xf9, 0x00, 0x93, 0x5d, 0x5b, 0x7f, 0xf7, 0xa3, 0x3c, 0x5c, 0xfb, 0xeb, 0xc9, 0x31, 0xc0,
	0x2f, 0xbb, 0x10, 0xea, 0xd0, 0xac, 0xad, 0xd4, 0x70, 0xf7, 0x9e, 0x8c, 0xa1, 0xbe, 0xea, 0xa0,
	0xd5, 0x0f, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x28, 0x7f, 0xe0, 0x23, 0x3a, 0x08, 0x00, 0x00,
}
